### ISSUE TITLE
Disable Cell Mon

### ISSUE THREAD

**Issue by plinytheelder** [UnownHash/Golbat#147]
Since we cannot currently send workers to identity cell mon (like what RDM does), can we at least add an option to disable them entirely?

**Comment by TurtIeSocks** [comment]
I believe this in your `config.toml` will solve that:
```toml
[[scan_rules]]
wild_pokemon = false
```
