### ISSUE TITLE
do not make gbl leagues configurable

### ISSUE THREAD

**Issue by ccev** [UnownHash/Golbat#70]
there is no point. it's only clutter

my suggestion:
```toml
[pvp]
enabled = true
include_hundos_under_cap = false
level_caps = [50, 51]
process_ultra = true
process_great = true
process_little = true
```

old:
```toml
[pvp]
enabled = true
include_hundos_under_cap = false
level_caps = [50, 51]

[[pvp.leagues]]
name = "little"
cap = 500
little = false

[[pvp.leagues]]
name = "great"
cap = 1500
little = false

[[pvp.leagues]]
name = "ultra"
cap = 2500
little = false
```
